services :
  db:
    image: postgres:17-alpine
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: task_manager
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080